classDiagram
  class Empresa {
    +UUID id
    +String nombre
    +String pais
    +String moneda
    +void registrarTransaccion(Transaccion t)
  }

  class Usuario {
    +UUID id
    +String nombre
    +String correo
    +RolUsuario rol
    +boolean activo
  }

  class Transaccion {
    +UUID id
    +Decimal monto
    +Date fecha
    +String descripcion
    +boolean registrar()
  }

  class Categoria {
    +UUID id
    +String nombre
    +TipoCategoria tipo
    +NaturalezaCosto naturaleza
  }

  Empresa "1" --> "*" Transaccion : registra
  Usuario "1" --> "*" Transaccion : realiza
  Transaccion "*" --> "1" Categoria : clasificada como