classDiagram
    class EmpresaTech {
    nombre = "TechPymes"
    idFiscal = "900112233-4"
    monedas = ["COP", "USD"]
    }
    
    class UsuarioAdmin {
        nombre = "Ana Ruiz"
        rol = "Administrador"
    }
    
    EmpresaTech --> UsuarioAdmin